spring:
##   datasource:
##    url: jdbc:mysql://127.0.0.1:3306/hydrogen?characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong&allowMultiQueries=true
##    username: root
##    password: "0621"
##    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
mybatis:
  type-aliases-package: com.sfan.hydro.domain
  mapper-locations: classpath:mybatis/*.xml
logging:
  config: classpath:log4j2.yaml