spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
mybatis:
  type-aliases-package: com.sfan.hydro.domain
  mapper-locations: classpath:mybatis/*.xml
logging:
  config: classpath:log4j2.yaml
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /HydroSys
  server:
    port: 12138
    address: 127.0.0.1

hydro:
  version: 0.0.1