database:
  ## 这里输入数据库名
  name: @database.name@
  ## 这里输入数据库地址
  host: @database.host@
  ## 这里输入数据库端口
  port: @database.port@
  ## 输入数据库账号和密码
  ## 密码若为0开头则需要写在引号中 example: "0000"
  userName: @database.user@
  password: @database.pwd@
